#!/bin/sh

if [ "$(id -u)" -ne 0 ]; then
	echo "Needs to run as root"
	exit 1
fi

PROC_0400="
/proc/interrupts
/proc/net/icmp
/proc/net/icmp6
/proc/net/tcp
/proc/net/tcp6
/proc/net/udp
/proc/net/udp6
/proc/net/unix
"

chmod 0400 $PROC_0400

procmount=$(grep -m 1 ^proc /proc/mounts)
if ! [[ "$procmount" == *"hidepid=invisible"* ]]; then
	echo "WARNING: hidepid=invisible not set for mount options"
fi
